# Generated by Django 2.2.3 on 2019-07-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0002_headermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headermodel',
            name='background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
