# Generated by Django 2.2.3 on 2019-07-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0004_footermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_site.FooterModel')),
            ],
        ),
    ]
