# Generated by Django 2.2.3 on 2019-07-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0005_footericon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('subtitle', models.CharField(blank=True, max_length=455, null=True)),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
