# Generated by Django 2.2.3 on 2019-07-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0006_articlesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
