# Generated by Django 2.2.3 on 2019-07-14 10:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0007_articlesmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='headermodel',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
