# Generated by Django 2.2.3 on 2019-07-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0009_auto_20190714_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
