# Generated by Django 2.2.3 on 2019-07-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0012_postmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
