# Generated by Django 2.2.3 on 2019-07-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0015_postmodel_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
